{
 "title": "Ledgerly",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bank",
    "label": "Bank",
    "query": "SELECT DISTINCT(bank) FROM accounts"
   }
  ]
 },
 "panels": [
  {
   "title": "(Checking Account) Monthly Net Cash Flow",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  i.year_month,\n  i.sum_amount AS \"In-Flow\",\n  i.sum_amount + o.sum_amount AS \"Net-Flow\",\n  o.sum_amount AS \"Out-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  {
   "title": "Total In-Flow ($)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  SUM(i.sum_amount) AS \"Total In-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  {
   "title": "Total Out-Flow ($)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  SUM(o.sum_amount) AS \"Total Out-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  {
   "title": "Total Net-Flow ($)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  SUM(i.sum_amount + o.sum_amount) AS \"Total Net-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  {
   "title": "Average In-Flow ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  AVG(i.sum_amount) AS \"Average In-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  {
   "title": "Average Out-Flow ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  AVG(o.sum_amount) AS \"Average Out-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  {
   "title": "Average In-Flow ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH inflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n), outflow AS (\n  SELECT \n    TO_CHAR(t.date, 'YYYY-MM') AS year_month,\n    SUM(t.amount) AS sum_amount\n  FROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND a.bank = '$bank'\n    AND t.flow_type = 'outflow'\n    AND $__timeFilter(t.date)\n  GROUP BY year_month\n  ORDER BY year_month\n)\nSELECT\n  AVG(i.sum_amount + o.sum_amount) AS \"Average Net-Flow\"\nFROM inflow AS i\nJOIN outflow AS o ON i.year_month = o.year_month\n"
    }
   ]
  },
  { "title": "Income Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average Income (Bi-Weekly)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "WITH bounds AS (\n  SELECT\n    a.account_type,\n    percentile_cont(0.05) WITHIN GROUP (ORDER BY t.amount) AS p05,\n    percentile_cont(0.95) WITHIN GROUP (ORDER BY t.amount) AS p95\n  FROM transactions AS t\n  JOIN accounts a ON t.account_id = a.account_id\n  WHERE $__timeFilter(t.date)\n    AND t.merchant = 'Payroll'\n  GROUP BY a.account_type\n), \nfiltered_avgs AS (\n  SELECT\n    a.account_type,\n    AVG(t.amount) AS avg_amount\n  FROM transactions t\n  JOIN accounts a ON t.account_id = a.account_id\n  JOIN bounds b\n    ON b.account_type = a.account_type\n  WHERE $__timeFilter(t.date)\n    AND t.amount BETWEEN b.p05 AND b.p95\n  GROUP BY a.account_type\n)\nSELECT\n  ROUND(SUM(avg_amount), 2) AS total_avg\nFROM filtered_avgs;"
    }
   ]
  },
  {
   "title": "Other Incomes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "SELECT SUM(amount) AS \"Total Income\"\nFROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND (t.subcategory != 'Savings Transfers'\n      AND t.merchant != 'Payroll')\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)"
    }
   ]
  },
  {
   "title": "Other Inflows",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 14 },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "SELECT \n  TO_CHAR(t.date, 'YYYY-MM-DD') AS \"Date\",\n  t.merchant AS \"Merchant\",\n  t.category AS \"Category\",\n  t.amount AS \"Amount\"\nFROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND (t.subcategory != 'Savings Transfers'\n      AND t.merchant != 'Payroll')\n    AND t.flow_type = 'inflow'\n    AND $__timeFilter(t.date)\nORDER BY \"Date\""
    }
   ]
  },
  {
   "title": "Total Payroll Income",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "SELECT SUM(amount) AS \"Total Income\"\nFROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND t.merchant = 'Payroll'\n    AND $__timeFilter(t.date)"
    }
   ]
  },
  {
   "title": "All Savings Transfers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ledgerly_db",
     "rawSql": "SELECT SUM(amount) AS \"Total Income\"\nFROM transactions AS t\n  JOIN accounts AS a ON t.account_id = a.account_id\n  WHERE a.account_type = 'Checking'\n    AND t.subcategory = 'Savings Transfers'\n    AND $__timeFilter(t.date)"
    }
   ]
  },
  {
   "title": "Current Month -- Expense Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n)\nSELECT\n  TO_CHAR(date_trunc('month', date), 'YYYY-MM') AS \"Current Month\"\nFROM transactions, latest_month\nWHERE date_trunc('month', date) = latest_month.month_start\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Total Inflow",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 45 },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n)\nSELECT\n  SUM(amount) AS current_expenses\nFROM transactions, latest_month\nWHERE date_trunc('month', date) = latest_month.month_start\n  AND flow_type = 'inflow'\n"
      }
     ]
    },
    {
     "title": "Total Outflow",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 45 },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n)\nSELECT\n  SUM(amount) AS current_expenses\nFROM transactions, latest_month\nWHERE date_trunc('month', date) = latest_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\n"
      }
     ]
    },
    {
     "title": "Expense Gauge",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 72 },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n)\nSELECT\n  subcategory,\n  SUM(amount) * -1 AS current_expenses\nFROM transactions, latest_month\nWHERE date_trunc('month', date) = latest_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\nGROUP BY subcategory\nORDER BY current_expenses;"
      }
     ]
    },
    {
     "title": "Recurring Expenses by Category",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n)\nSELECT\n  category,\n  SUM(amount) AS current_expenses\nFROM transactions, latest_month\nWHERE date_trunc('month', date) = latest_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\nGROUP BY category\nORDER BY current_expenses;"
      }
     ]
    },
    {
     "title": "Recurring Expenses by Merchant",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 13, "x": 9, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n)\nSELECT\n  merchant,\n  SUM(amount) AS current_expenses\nFROM transactions, latest_month\nWHERE date_trunc('month', date) = latest_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\nGROUP BY merchant\nORDER BY current_expenses;"
      }
     ]
    }
   ]
  },
  {
   "title": "Previous Month -- Expense Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": " ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_full_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n  WHERE date_trunc('month', date) < date_trunc('month', CURRENT_DATE)\n)\nSELECT\n  TO_CHAR(date_trunc('month', date), 'YYYY-MM') AS \"Previous Month\"\nFROM transactions, latest_full_month\nWHERE date_trunc('month', date) = latest_full_month.month_start\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Total Inflow",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_full_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n  WHERE date_trunc('month', date) < date_trunc('month', CURRENT_DATE)\n)\nSELECT\n  SUM(amount) AS current_expenses\nFROM transactions, latest_full_month\nWHERE date_trunc('month', date) = latest_full_month.month_start\n  AND flow_type = 'inflow'\n"
      }
     ]
    },
    {
     "title": "Total Outflow",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 46 },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_full_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n  WHERE date_trunc('month', date) < date_trunc('month', CURRENT_DATE)\n)\nSELECT\n  SUM(amount) AS current_expenses\nFROM transactions, latest_full_month\nWHERE date_trunc('month', date) = latest_full_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\n"
      }
     ]
    },
    {
     "title": "Expense Gauge",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 51 },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_full_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n  WHERE date_trunc('month', date) < date_trunc('month', CURRENT_DATE)\n)\nSELECT\n  subcategory,\n  SUM(amount) * -1 AS current_expenses\nFROM transactions, latest_full_month\nWHERE date_trunc('month', date) = latest_full_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\nGROUP BY subcategory\nORDER BY current_expenses;"
      }
     ]
    },
    {
     "title": "Recurring Expenses by Category",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_full_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n  WHERE date_trunc('month', date) < date_trunc('month', CURRENT_DATE)\n)\nSELECT\n  category,\n  SUM(amount) AS current_expenses\nFROM transactions, latest_full_month\nWHERE date_trunc('month', date) = latest_full_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\nGROUP BY category\nORDER BY current_expenses;"
      }
     ]
    },
    {
     "title": "Recurring Expenses by Merchant",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 13, "x": 9, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "ledgerly_db",
       "rawSql": "WITH latest_full_month AS (\n  SELECT MAX(date_trunc('month', date)) AS month_start\n  FROM transactions\n  WHERE date_trunc('month', date) < date_trunc('month', CURRENT_DATE)\n)\n\nSELECT\n  merchant,\n  SUM(amount) AS current_expenses\nFROM transactions, latest_full_month\nWHERE date_trunc('month', date) = latest_full_month.month_start\n  AND flow_type = 'outflow'\n  AND is_recurring = 't'\nGROUP BY merchant\nORDER BY current_expenses;"
      }
     ]
    }
   ]
  }
 ]
}